### ISSUE TITLE
No for loop like it says in README

### ISSUE THREAD

**Issue by w3b-net-au** [bkiers/Mu#1]
There is no for loop like it says in the README, I have attempted to play around with ANTLR basics and added the for loop in my fork of Mu.

[My fork of Mu](https://github.com/w3b-net-au/Mu)

- FOR ID = (INT|FLOAT) TO (INT|FLOAT)  statements  NEXT
- Changed the syntax slightly to remove semicolons
- Added string interpolation with the "dollar string" like $"var = {var}"
- Added an unless conditional

Thanks very much for Mu, it's a wonderful example of using ANTLR.  I plan to add a "standard library" of sorts, and expand it to include function definitions and calls, and later basic object orientation.

It would certainly be nice to generate C# or C++ code instead, generate an exe, and have a standalone Mu interpreter!

**Comment by bkiers** [comment]
You're most welcome. And thanks: I removed the remark about the `for` statement and added a link to your forked repo.
